# Micronaut
micronaut.application.name=crudUsers
micronaut.server.port=8080

# PostgreSQL
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.url=jdbc:postgresql://localhost:5432/treinamento
datasources.default.username=postgres
datasources.default.password=root

# MongoDB
mongodb.uri=mongodb://localhost:27017/treinamento

# JPA / Hibernate
jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jpa.default.properties.hibernate.show_sql=true
jpa.default.properties.hibernate.format_sql=true
micronaut.data.datasource.default.dialect=POSTGRES
micronaut.data.hibernate.jpa.enabled=true

# Swagger / OpenAPI
micronaut.router.static-resources.swagger.paths=classpath:META-INF/swagger
micronaut.router.static-resources.swagger.mapping=/swagger/**
micronaut.router.static-resources.swagger-ui.paths=classpath:META-INF/swagger/views/swagger-ui
micronaut.router.static-resources.swagger-ui.mapping=/swagger-ui/**
micronaut.openapi.views.spec=swagger-ui.enabled=true,redoc.enabled=true
micronaut.openapi.expand.api.packages=com.example

# Kafka
kafka.bootstrap.servers=localhost:9092

# Topics
kafka.topics.error=topic-error
kafka.topics.warn-info=warn-info-topic

# Producer config
kafka.producers.default.acks=all
kafka.producers.default.retries=3
kafka.producers.default.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producers.default.value-serializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer

# Consumer config
kafka.consumers.default.specific.protobuf.value.type=com.crud.entities.protoBuf.LogMessageProto

# CORS configuration
micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.web.allowed-origins=http://localhost:5173
#micronaut.server.cors.configurations.web.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#micronaut.server.cors.configurations.web.allowed-headers=Content-Type,Authorization,Accept,Origin,X-Requested-With
#micronaut.server.cors.configurations.web.allow-credentials=true